
spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2

        - id: posts-service
          uri: lb://POSTS-SERVICE
          predicates:
            - Path=/api/v1/posts/**
          filters:
            - StripPrefix=2

        - id: connections-service
          uri: lb://CONNECTION-SSERVICE
          predicates:
            - Path=/api/v1/connections/**
          filters:
            - StripPrefix=2

